version: '3'
services:
  web:
    image: dev-hmp 
    build: ./userapi
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./userapi:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"